version: "3.8"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Конфігурація Nginx
      - ./nginx:/usr/share/nginx/html  # Папка зі статичними файлами
    depends_on:
      - node-app

networks:
  app-network:
    driver: bridge
